#!/bin/sh
# Based on https://medium.com/@mmessell/apply-spotless-formatting-with-git-pre-commit-hook-1c484ea68c34
# install by running `git config core.hooksPath utils/git-hooks` in your repo root
# Based on an edited version from https://github.com/Wynntils/Artemis

echo '[git hook] executing format_urls.sh before commit'

# Get list of staged files
stagedFiles=$(git diff --staged --name-only)

./Utils/hash_urls.sh
./Utils/format_urls.sh

# Store the last exit code
RESULT=$?

# Re-add possibly modified files to the git stage area
for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done

# Return the './gradlew spotlessApply' exit code
exit $RESULT
