#!/bin/bash

BASE_DIR="$(cd $(dirname "$0")/.. 2>/dev/null && pwd)"
ASSETS_DIR="$BASE_DIR/Generators/assets/minecraft/items"
OUTPUT_JSON="$BASE_DIR/Data-Storage/model_data.json"
TEMP_OUTPUT="$OUTPUT_JSON.tmp"

# All items come under item/wynn
MODEL_BASE="item/wynn"

# Ensure resource pack exists
if [ ! -d "$BASE_DIR/Generators/assets" ]; then
  echo "Resource pack not found, place \"assets\" directory inside \"Generators\" directory"
  exit 1
fi

# Define the looks
# 2 Formats
# 1. "key|model_suffix"
# 2. "key|model_suffix|type"
# key is how the mod will lookup the model data
# model_suffix is what comes after the "item/wynn/" for the model. Can be defined in the lookup or ignored and it will
# need to be defined in the process_group call.
# If looking for multiple model types, separate them with a "," e.g. "weapon/archer,skin/bow"
# type is how the value should be stored. Currently supports: float or range. Not including one will assume float
# Split lookups per item, define the filename when calling process_group
LOOKUPS_BOWS=(
  "bow.basicWood|bow_basic_wood"
  "bow.basicGold|bow_basic_gold"
  "bow.air1|bow_air_a"
  "bow.air2|bow_air_b"
  "bow.air3|bow_air_c"
  "bow.earth1|bow_earth_a"
  "bow.earth2|bow_earth_b"
  "bow.earth3|bow_earth_c"
  "bow.fire1|bow_fire_a"
  "bow.fire2|bow_fire_b"
  "bow.fire3|bow_fire_c"
  "bow.thunder1|bow_thunder_a"
  "bow.thunder2|bow_thunder_b"
  "bow.thunder3|bow_thunder_c"
  "bow.water1|bow_water_a"
  "bow.water2|bow_water_b"
  "bow.water3|bow_water_c"
  "bow.multi1|bow_multi_a"
  "bow.multi2|bow_multi_b"
  "bow.multi3|bow_multi_c"
)
  
LOOKUPS_DAGGERS=(
  "dagger.basicWood|dagger_basic_wood"
  "dagger.basicGold|dagger_basic_gold"
  "dagger.air1|dagger_air_a"
  "dagger.air2|dagger_air_b"
  "dagger.air3|dagger_air_c"
  "dagger.earth1|dagger_earth_a"
  "dagger.earth2|dagger_earth_b"
  "dagger.earth3|dagger_earth_c"
  "dagger.fire1|dagger_fire_a"
  "dagger.fire2|dagger_fire_b"
  "dagger.fire3|dagger_fire_c"
  "dagger.thunder1|dagger_thunder_a"
  "dagger.thunder2|dagger_thunder_b"
  "dagger.thunder3|dagger_thunder_c"
  "dagger.water1|dagger_water_a"
  "dagger.water2|dagger_water_b"
  "dagger.water3|dagger_water_c"
  "dagger.multi1|dagger_multi_a"
  "dagger.multi2|dagger_multi_b"
  "dagger.multi3|dagger_multi_c"
)
  
LOOKUPS_WANDS=(
  "wand.basicWood|wand_basic_wood"
  "wand.basicGold|wand_basic_gold"
  "wand.basicDiamond|wand_basic_diamond"
  "wand.air1|wand_air_a"
  "wand.air2|wand_air_b"
  "wand.air3|wand_air_c"
  "wand.earth1|wand_earth_a"
  "wand.earth2|wand_earth_b"
  "wand.earth3|wand_earth_c"
  "wand.fire1|wand_fire_a"
  "wand.fire2|wand_fire_b"
  "wand.fire3|wand_fire_c"
  "wand.thunder1|wand_thunder_a"
  "wand.thunder2|wand_thunder_b"
  "wand.thunder3|wand_thunder_c"
  "wand.water1|wand_water_a"
  "wand.water2|wand_water_b"
  "wand.water3|wand_water_c"
  "wand.multi1|wand_multi_a"
  "wand.multi2|wand_multi_b"
  "wand.multi3|wand_multi_c"
)
  
LOOKUPS_RELIKS=(
  "relik.basicWood|relik_basic_wooden"
  "relik.basicGold|relik_basic_gold"
  "relik.air1|relik_air_a"
  "relik.air2|relik_air_b"
  "relik.air3|relik_air_c"
  "relik.earth1|relik_earth_a"
  "relik.earth2|relik_earth_b"
  "relik.earth3|relik_earth_c"
  "relik.fire1|relik_fire_a"
  "relik.fire2|relik_fire_b"
  "relik.fire3|relik_fire_c"
  "relik.thunder1|relik_thunder_a"
  "relik.thunder2|relik_thunder_b"
  "relik.thunder3|relik_thunder_c"
  "relik.water1|relik_water_a"
  "relik.water2|relik_water_b"
  "relik.water3|relik_water_c"
  "relik.multi1|relik_multi_a"
  "relik.multi2|relik_multi_b"
  "relik.multi3|relik_multi_c"
)
  
LOOKUPS_SPEARS=(
  "spear.basicWood|spear_basic_wood"
  "spear.basicGold|spear_basic_gold"
  "spear.air1|spear_air_a"
  "spear.air2|spear_air_b"
  "spear.air3|spear_air_c"
  "spear.earth1|spear_earth_a"
  "spear.earth2|spear_earth_b"
  "spear.earth3|spear_earth_c"
  "spear.fire1|spear_fire_a"
  "spear.fire2|spear_fire_b"
  "spear.fire3|spear_fire_c"
  "spear.thunder1|spear_thunder_a"
  "spear.thunder2|spear_thunder_b"
  "spear.thunder3|spear_thunder_c"
  "spear.water1|spear_water_a"
  "spear.water2|spear_water_b"
  "spear.water3|spear_water_c"
  "spear.multi1|spear_multi_a"
  "spear.multi2|spear_multi_b"
  "spear.multi3|spear_multi_c"
)
  
LOOKUPS_RINGS=(
  "ring.basicIron|ring_base_a"
  "ring.basicGold|ring_base_b"
  "ring.basicGem|ring_special_c"
  "ring.basicPearl|ring_special_b"
  "ring.basicWedding|ring_special_a"
  "ring.air1|ring_air_a"
  "ring.air2|ring_air_b"
  "ring.earth1|ring_earth_a"
  "ring.earth2|ring_earth_b"
  "ring.fire1|ring_fire_a"
  "ring.fire2|ring_fire_b"
  "ring.thunder1|ring_thunder_a"
  "ring.thunder2|ring_thunder_b"
  "ring.water1|ring_water_a"
  "ring.water2|ring_water_b"
  "ring.multi1|ring_multi_a"
  "ring.multi2|ring_multi_b"
)
  
LOOKUPS_BRACELETS=(
  "bracelet.basicIron|bracelet_base_a"
  "bracelet.basicGold|bracelet_base_b"
  "bracelet.air1|bracelet_air_a"
  "bracelet.air2|bracelet_air_b"
  "bracelet.earth1|bracelet_earth_a"
  "bracelet.earth2|bracelet_earth_b"
  "bracelet.fire1|bracelet_fire_a"
  "bracelet.fire2|bracelet_fire_b"
  "bracelet.thunder1|bracelet_thunder_a"
  "bracelet.thunder2|bracelet_thunder_b"
  "bracelet.water1|bracelet_water_a"
  "bracelet.water2|bracelet_water_b"
  "bracelet.multi1|bracelet_multi_a"
  "bracelet.multi2|bracelet_multi_b"
)
  
LOOKUPS_NECKLACES=(
  "necklace.basicIron|necklace_base_a"
  "necklace.basicGold|necklace_base_b"
  "necklace.basicCross|necklace_special_a"
  "necklace.basicBroach|necklace_special_b"
  "necklace.basicPearl|necklace_special_c"
  "necklace.air1|necklace_air_a"
  "necklace.air2|necklace_air_b"
  "necklace.earth1|necklace_earth_a"
  "necklace.earth2|necklace_earth_b"
  "necklace.fire1|necklace_fire_a"
  "necklace.fire2|necklace_fire_b"
  "necklace.thunder1|necklace_thunder_a"
  "necklace.thunder2|necklace_thunder_b"
  "necklace.water1|necklace_water_a"
  "necklace.water2|necklace_water_b"
  "necklace.multi1|necklace_multi_a"
  "necklace.multi2|necklace_multi_b"
)

LOOKUPS_CHARMS=(
  "charm.worm|worm"
  "charm.light|light"
  "charm.stone|stone"
  "charm.void|void"
  "charm.corruption|corruption"
)

LOOKUPS_TOMES=(
  "tome.armour|armour"
  "tome.guild|guild"
  "tome.lootrun|lootrun"
  "tome.mana|mana"
  "tome.movement|movement"
  "tome.utility|utility"
  "tome.weapon|weapon"
)

LOOKUPS_INGREDIENTS=(
  "ingredient.7YottabyteStorageComponent|7_yottabyte_storage_component"
  "ingredient.accursedEffigy|accursed_effigy"
  "ingredient.acidMagma|acid_magma"
  "ingredient.acidicBlood|acidic_blood"
  "ingredient.acidicRemains|acidic_remains"
  "ingredient.acidicSolution|acidic_solution"
  "ingredient.acidulousPlating|acidulous_plating"
  "ingredient.activeFireball|active_fireball"
  "ingredient.adamastorsFaceplate|adamastors_faceplate"
  "ingredient.adaptiveTissue|adaptive_tissue"
  "ingredient.adventurersDiary|adventurers_diary"
  "ingredient.agedCheese|aged_cheese"
  "ingredient.medallion|medallion"
  "ingredient.agedTome|aged_tome"
  "ingredient.agulloBeak|agullo_beak"
  "ingredient.alga|alga"
  "ingredient.algaeMat|algae_mat"
  "ingredient.alginateDressing|alginate_dressing"
  "ingredient.alnamarMeat|alnamar_meat"
  "ingredient.alteredAsh|altered_ash"
  "ingredient.altitudeShard|altitude_shard"
  "ingredient.ancientCoins|ancient_coins"
  "ingredient.ancientCore|ancient_core"
  "ingredient.ancientCurrency|ancient_currency"
  "ingredient.ancientHeart|ancient_heart"
  "ingredient.ancientMetal|ancient_metal"
  "ingredient.ancientMoss|ancient_moss"
  "ingredient.ancientPanel|ancient_panel"
  "ingredient.ancientScripture|ancient_scripture"
  "ingredient.ancientSpringWater|ancient_spring_water"
  "ingredient.angelsBlessing|angels_blessing"
  "ingredient.angelicGem|angelic_gem"
  "ingredient.anglersLight|anglers_light"
  "ingredient.antiqueMetal|antique_metal"
  "ingredient.antlerFragment|antler_fragment"
  "ingredient.apple|apple"
  "ingredient.aquaVitae|aqua_vitae"
  "ingredient.aquaticBeauty|aquatic_beauty"
  "ingredient.arcaneAnomaly|arcane_anomaly"
  "ingredient.archaicMedallion|archaic_medallion"
  "ingredient.ashenHide|ashen_hide"
  "ingredient.ashstainedBasalt|ashstained_basalt"
  "ingredient.aspectOfTheVoid|aspect_of_the_void"
  "ingredient.assortedSeeds|assorted_seeds"
  "ingredient.astralAlloy|astral_alloy"
  "ingredient.azureBlossom|azure_blossom"
  "ingredient.ballOfSlime|ball_of_slime"
  "ingredient.bamboo|bamboo"
  "ingredient.banditRations|bandit_rations"
  "ingredient.barbedStinger|barbed_stinger"
  "ingredient.batEar|bat_ear"
  "ingredient.batHeart|bat_heart"
  "ingredient.beakOfTheNivlanBeauty|beak_of_the_nivlan_beauty"
  "ingredient.beastialViscera|beastial_viscera"
  "ingredient.beefTongue|beef_tongue"
  "ingredient.bigCarapace|big_carapace"
  "ingredient.bigJawbreaker|big_jawbreaker"
  "ingredient.bioluminescentBlood|bioluminescent_blood"
  "ingredient.bioluminescentMoss|bioluminescent_moss"
  "ingredient.bionicFiber|bionic_fiber"
  "ingredient.blackHole|black_hole"
  "ingredient.blackSteel|black_steel"
  "ingredient.blackSulphur|black_sulphur"
  "ingredient.blazePowder|blaze_powder"
  "ingredient.blazingFireball|blazing_fireball"
  "ingredient.blazingStimulants|blazing_stimulants"
  "ingredient.blessedHeart|blessed_heart"
  "ingredient.blightedBrain|blighted_brain"
  "ingredient.bloatedArtery|bloated_artery"
  "ingredient.bloodOfTheNivlanBeauty|blood_of_the_nivlan_beauty"
  "ingredient.bloodstainedRemains|bloodstained_remains"
  "ingredient.bloodstainedSteel|bloodstained_steel"
  "ingredient.bloodweb|bloodweb"
  "ingredient.boarMeat|boar_meat"
  "ingredient.bobsTear|bobs_tear"
  "ingredient.boneAsh|bone_ash"
  "ingredient.boneMeal|bone_meal"
  "ingredient.bottledDecay|bottled_decay"
  "ingredient.bottledFairy|bottled_fairy"
  "ingredient.bottomlessEmeraldPouch|bottomless_emerald_pouch"
  "ingredient.braveheart|braveheart"
  "ingredient.brightPetal|bright_petal"
  "ingredient.brokenAmulet|broken_amulet"
  "ingredient.brokenAnticBead|broken_antic_bead"
  "ingredient.brokenDagger|broken_dagger"
  "ingredient.brokenFiddle|broken_fiddle"
  "ingredient.brokenHelmet|broken_helmet"
  "ingredient.brokenPick|broken_pick"
  "ingredient.brokenRamHorn|broken_ram_horn"
  "ingredient.brokenSteelBlade|broken_steel_blade"
  "ingredient.brokenSteelHook|broken_steel_hook"
  "ingredient.brownMushroom|brown_mushroom"
  "ingredient.bugParts|bug_parts"
  "ingredient.burialTalisman|burial_talisman"
  "ingredient.burningSoul|burning_soul"
  "ingredient.butterflyBuckler|butterfly_buckler"
  "ingredient.calcifiedLigament|calcified_ligament"
  "ingredient.calmedThunder|calmed_thunder"
  "ingredient.candyButton|candy_button"
  "ingredient.canyonParsley|canyon_parsley"
  "ingredient.captainsGlass|captains_glass"
  "ingredient.carapaceFragment|carapace_fragment"
  "ingredient.cardboardBat|cardboard_bat"
  "ingredient.catFood|cat_food"
  "ingredient.catTail|cat_tail"
  "ingredient.catsEars|cats_ears"
  "ingredient.cataratite|cataratite"
  "ingredient.cavitatedBone|cavitated_bone"
  "ingredient.ceruleanRectrix|cerulean_rectrix"
  "ingredient.chainLoop|chain_loop"
  "ingredient.chaoticEmbers|chaotic_embers"
  "ingredient.charcoalLump|charcoal_lump"
  "ingredient.charredBone|charred_bone"
  "ingredient.charredCarapace|charred_carapace"
  "ingredient.cherishedHeirloom|cherished_heirloom"
  "ingredient.cherrySapling|cherry_sapling"
  "ingredient.chippedQuartz|chipped_quartz"
  "ingredient.chitinPlate|chitin_plate"
  "ingredient.chromaticBloom|chromatic_bloom"
  "ingredient.chunkyAsh|chunky_ash"
  "ingredient.clawOfDemise|claw_of_demise"
  "ingredient.cleanedSaccharum|cleaned_saccharum"
  "ingredient.climbersPadding|climbers_padding"
  "ingredient.cloudtwine|cloudtwine"
  "ingredient.coagulatedBloodGelatin|coagulated_blood_gelatin"
  "ingredient.coagulatedClot|coagulated_clot"
  "ingredient.coastalSand|coastal_sand"
  "ingredient.coastalShell|coastal_shell"
  "ingredient.cocoaCaps|cocoa_caps"
  "ingredient.colossusShard|colossus_shard"
  "ingredient.combustionShard|combustion_shard"
  "ingredient.commanderSpyglass|commander_spyglass"
  "ingredient.compressedPowders|compressed_powders"
  "ingredient.condensedDarkness|condensed_darkness"
  "ingredient.condorFeather|condor_feather"
  "ingredient.conflagrite|conflagrite"
  "ingredient.congealedSlime|congealed_slime"
  "ingredient.congealingViscera|congealing_viscera"
  "ingredient.conscriptionLetter|conscription_letter"
  "ingredient.consecratedIvory|consecrated_ivory"
  "ingredient.contrabandAbsinthe|contraband_absinthe"
  "ingredient.contrabandHibiscus|contraband_hibiscus"
  "ingredient.contrabandMiracleBerry|contraband_miracle_berry"
  "ingredient.corbysInnards|corbys_innards"
  "ingredient.cornHusk|corn_husk"
  "ingredient.corrodedChunk|corroded_chunk"
  "ingredient.corruptedBeef|corrupted_beef"
  "ingredient.corruptedBracken|corrupted_bracken"
  "ingredient.corruptedFragment|corrupted_fragment"
  "ingredient.corruptedIchor|corrupted_ichor"
  "ingredient.corruptedMetalScrap|corrupted_metal_scrap"
  "ingredient.corruptionShard|corruption_shard"
  "ingredient.cortrichEggs|cortrich_eggs"
  "ingredient.coyoteFang|coyote_fang"
  "ingredient.crabLegs|crab_legs"
  "ingredient.crackedGeode|cracked_geode"
  "ingredient.crackedSkin|cracked_skin"
  "ingredient.crawlerEye|crawler_eye"
  "ingredient.crawlerSludge|crawler_sludge"
  "ingredient.crawlerWeb|crawler_web"
  "ingredient.crazyHorseGlue|crazy_horse_glue"
  "ingredient.creepvineCluster|creepvine_cluster"
  "ingredient.crumblyRock|crumbly_rock"
  "ingredient.crumpledPropaganda|crumpled_propaganda"
  "ingredient.crystalDust|crystal_dust"
  "ingredient.crystallineGrowth|crystalline_growth"
  "ingredient.crystallizedOrgan|crystallized_organ"
  "ingredient.cultistAshes|cultist_ashes"
  "ingredient.curseGland|curse_gland"
  "ingredient.cursedAshes|cursed_ashes"
  "ingredient.cursedVenomSac|cursed_venom_sac"
  "ingredient.cursedWings|cursed_wings"
  "ingredient.cycloneBlueLeaves|cyclone_blue_leaves"
  "ingredient.cysticLard|cystic_lard"
  "ingredient.dampHairs|damp_hairs"
  "ingredient.darkIris|dark_iris"
  "ingredient.darkMatter|dark_matter"
  "ingredient.deadNavalShard|dead_naval_shard"
  "ingredient.deathWhistleLeaf|death_whistle_leaf"
  "ingredient.decayingArteries|decaying_arteries"
  "ingredient.decayingSkin|decaying_skin"
  "ingredient.deceptivelyLargeBag|deceptively_large_bag"
  "ingredient.decomposingSnapdragon|decomposing_snapdragon"
  "ingredient.deepIceCore|deep_ice_core"
  "ingredient.deepbornScavenger|deepborn_scavenger"
  "ingredient.defectiveCircuits|defective_circuits"
  "ingredient.defendersStone|defenders_stone"
  "ingredient.defiledLuxroot|defiled_luxroot"
  "ingredient.defishious|defishious"
  "ingredient.delectableEscargot|delectable_escargot"
  "ingredient.delectableMorsel|delectable_morsel"
  "ingredient.demonicAshes|demonic_ashes"
  "ingredient.demonicBlood|demonic_blood"
  "ingredient.denseVoidHoleChunk|dense_void_hole_chunk"
  "ingredient.depreciatingFlesh|depreciating_flesh"
  "ingredient.depthsGem|depths_gem"
  "ingredient.depurinatedGenome|depurinated_genome"
  "ingredient.dernicHydroid|dernic_hydroid"
  "ingredient.dernicParasite|dernic_parasite"
  "ingredient.dernicSludgebomb|dernic_sludgebomb"
  "ingredient.desertFossil|desert_fossil"
  "ingredient.devilishDelight|devilish_delight"
  "ingredient.digestibleFungi|digestible_fungi"
  "ingredient.discardedJunk|discarded_junk"
  "ingredient.diseasedFluids|diseased_fluids"
  "ingredient.disturbedDye|disturbed_dye"
  "ingredient.dogunAlertSigil|dogun_alert_sigil"
  "ingredient.dominantForce|dominant_force"
  "ingredient.doomStone|doom_stone"
  "ingredient.draconicBoneMarrow|draconic_bone_marrow"
  "ingredient.dragonAura|dragon_aura"
  "ingredient.dragonlingEgg|dragonling_egg"
  "ingredient.dragonlingScale|dragonling_scale"
  "ingredient.drainedBone|drained_bone"
  "ingredient.driedGill|dried_gill"
  "ingredient.driedKelp|dried_kelp"
  "ingredient.dryBone|dry_bone"
  "ingredient.drySeeds|dry_seeds"
  "ingredient.durableSkin|durable_skin"
  "ingredient.earthenwareClay|earthenware_clay"
  "ingredient.earthlyAura|earthly_aura"
  "ingredient.earthlyPebble|earthly_pebble"
  "ingredient.egg|egg"
  "ingredient.electromagneticShieldPlating|electromagnetic_shield_plating"
  "ingredient.electroplasm|electroplasm"
  "ingredient.elephantToenail|elephant_toenail"
  "ingredient.elephelkTrunk|elephelk_trunk"
  "ingredient.emergencyStimulant|emergency_stimulant"
  "ingredient.emptyCasings|empty_casings"
  "ingredient.enchantedChainLink|enchanted_chain_link"
  "ingredient.energeticAura|energetic_aura"
  "ingredient.engravedTablet|engraved_tablet"
  "ingredient.enhancedBehaviourMicrochip|enhanced_behaviour_microchip"
  "ingredient.enhancedDynamicsMicrochip|enhanced_dynamics_microchip"
  "ingredient.enhancedPathfindingMicrochip|enhanced_pathfinding_microchip"
  "ingredient.enhancedPhysicsMicrochip|enhanced_physics_microchip"
  "ingredient.enhancedPostProcessingMicrochip|enhanced_post_processing_microchip"
  "ingredient.enhancedPotentialMicrochip|enhanced_potential_microchip"
  "ingredient.enragedSoul|enraged_soul"
  "ingredient.essenceOfDusk|essence_of_dusk"
  "ingredient.essenceOfDissolution|essence_of_dissolution"
  "ingredient.eternalFlame|eternal_flame"
  "ingredient.ethericFern|etheric_fern"
  "ingredient.evictionNotice|eviction_notice"
  "ingredient.evolvingSpores|evolving_spores"
  "ingredient.expelledShrapnel|expelled_shrapnel"
  "ingredient.exquisiteMarshScale|exquisite_marsh_scale"
  "ingredient.extremelyDensePebble|extremely_dense_pebble"
  "ingredient.extremophilePelt|extremophile_pelt"
  "ingredient.eyeOfTheBeast|eye_of_the_beast"
  "ingredient.faebloomPetal|faebloom_petal"
  "ingredient.fairyDust|fairy_dust"
  "ingredient.fairyPowder|fairy_powder"
  "ingredient.familiarEssence|familiar_essence"
  "ingredient.fancyPelt|fancy_pelt"
  "ingredient.farcorsTrust|farcors_trust"
  "ingredient.fathomfloodedFlesh|fathomflooded_flesh"
  "ingredient.featherOfGrace|feather_of_grace"
  "ingredient.felineClaws|feline_claws"
  "ingredient.fiberglassFrame|fiberglass_frame"
  "ingredient.fieryAura|fiery_aura"
  "ingredient.fieryEssence|fiery_essence"
  "ingredient.fightingStick|fighting_stick"
  "ingredient.filchedPurse|filched_purse"
  "ingredient.fireflyDust|firefly_dust"
  "ingredient.fishScales|fish_scales"
  "ingredient.fishTail|fish_tail"
  "ingredient.fissuredTablet|fissured_tablet"
  "ingredient.flameheart|flameheart"
  "ingredient.flashfrost|flashfrost"
  "ingredient.flerisiBark|flerisi_bark"
  "ingredient.fleshForgedCircuit|flesh_forged_circuit"
  "ingredient.floatStone|float_stone"
  "ingredient.flowOfFate|flow_of_fate"
  "ingredient.fluffyFur|fluffy_fur"
  "ingredient.flugsvampCap|flugsvamp_cap"
  "ingredient.fluidLight|fluid_light"
  "ingredient.flytrapFangs|flytrap_fangs"
  "ingredient.forestWeb|forest_web"
  "ingredient.forgottenAxe|forgotten_axe"
  "ingredient.forgottenPickaxe|forgotten_pickaxe"
  "ingredient.forsakenCatalyst|forsaken_catalyst"
  "ingredient.foulFairyDust|foul_fairy_dust"
  "ingredient.foulFluid|foul_fluid"
  "ingredient.foxCoat|fox_coat"
  "ingredient.fragmentation|fragmentation"
  "ingredient.freshBone|fresh_bone"
  "ingredient.freshGame|fresh_game"
  "ingredient.freshWater|fresh_water"
  "ingredient.frogEyeball|frog_eyeball"
  "ingredient.frostbittenFlesh|frostbitten_flesh"
  "ingredient.frostboundMemory|frostbound_memory"
  "ingredient.frozenGhostlyEssence|frozen_ghostly_essence"
  "ingredient.fumingLavaRock|fuming_lava_rock"
  "ingredient.fungiSpores|fungi_spores"
  "ingredient.galvanicStone|galvanic_stone"
  "ingredient.gelatinousSlimeChunk|gelatinous_slime_chunk"
  "ingredient.generatorChip|generator_chip"
  "ingredient.gertSkin|gert_skin"
  "ingredient.ghostlyEssence|ghostly_essence"
  "ingredient.ghostlyMembrane|ghostly_membrane"
  "ingredient.ghostlyPlume|ghostly_plume"
  "ingredient.giantIvoryTusk|giant_ivory_tusk"
  "ingredient.giantPetal|giant_petal"
  "ingredient.giantStinger|giant_stinger"
  "ingredient.giantSwordShard|giant_sword_shard"
  "ingredient.gildedBark|gilded_bark"
  "ingredient.gildedRegalia|gilded_regalia"
  "ingredient.glacialAnomaly|glacial_anomaly"
  "ingredient.glaiveHead|glaive_head"
  "ingredient.glimmeringBeak|glimmering_beak"
  "ingredient.glimmeringCoin|glimmering_coin"
  "ingredient.glisteningSlime|glistening_slime"
  "ingredient.glitteringSilt|glittering_silt"
  "ingredient.gloomyOrb|gloomy_orb"
  "ingredient.glowBulbSeeds|glow_bulb_seeds"
  "ingredient.glowingScales|glowing_scales"
  "ingredient.glowingTreeSap|glowing_tree_sap"
  "ingredient.goblinTooth|goblin_tooth"
  "ingredient.goblinTrinket|goblin_trinket"
  "ingredient.platinumIngot|platinum_ingot"
  "ingredient.goldBar|gold_bar"
  "ingredient.goldNugget|gold_nugget"
  "ingredient.goldTooth|gold_tooth"
  "ingredient.goldenAviaFeather|golden_avia_feather"
  "ingredient.goldenCoin|golden_coin"
  "ingredient.gollierIron|gollier_iron"
  "ingredient.graniteMaul|granite_maul"
  "ingredient.gravitationCrystal|gravitation_crystal"
  "ingredient.greenFin|green_fin"
  "ingredient.greenFoot|green_foot"
  "ingredient.greenOpal|green_opal"
  "ingredient.greenScale|green_scale"
  "ingredient.greyCloud|grey_cloud"
  "ingredient.grittyRocks|gritty_rocks"
  "ingredient.grookFeather|grook_feather"
  "ingredient.grookivaFeather|grookiva_feather"
  "ingredient.grootslangFin|grootslang_fin"
  "ingredient.gruesomeCarnassial|gruesome_carnassial"
  "ingredient.gunkfueledCore|gunkfueled_core"
  "ingredient.gunpowder|gunpowder"
  "ingredient.gyliaEssence|gylia_essence"
  "ingredient.halevaPlant|haleva_plant"
  "ingredient.haphazardSerum|haphazard_serum"
  "ingredient.hardenedIcicle|hardened_icicle"
  "ingredient.hardenedMagma|hardened_magma"
  "ingredient.hardenedMandible|hardened_mandible"
  "ingredient.harosBrokenBadge|haros_broken_badge"
  "ingredient.harpyBone|harpy_bone"
  "ingredient.harpyWing|harpy_wing"
  "ingredient.hatchlingRemnant|hatchling_remnant"
  "ingredient.helioWing|helio_wing"
  "ingredient.hellishCinders|hellish_cinders"
  "ingredient.herbalExtract|herbal_extract"
  "ingredient.herbstzeitlose|herbstzeitlose"
  "ingredient.highExplosive|high_explosive"
  "ingredient.highlandBasil|highland_basil"
  "ingredient.holyPowder|holy_powder"
  "ingredient.honouredCommandersMedal|honoured_commanders_medal"
  "ingredient.horseMane|horse_mane"
  "ingredient.huntersDisguise|hunters_disguise"
  "ingredient.hybridSkin|hybrid_skin"
  "ingredient.hydrofluoricAcid|hydrofluoric_acid"
  "ingredient.ibjubFruit|ibjub_fruit"
  "ingredient.iceFishingBait|ice_fishing_bait"
  "ingredient.iceFishingHook|ice_fishing_hook"
  "ingredient.iceFishingNet|ice_fishing_net"
  "ingredient.iceFishingTwine|ice_fishing_twine"
  "ingredient.iceSilver|ice_silver"
  "ingredient.iceSliver|ice_sliver"
  "ingredient.iceberries|iceberries"
  "ingredient.icyCrampons|icy_crampons"
  "ingredient.icyShard|icy_shard"
  "ingredient.igneousThread|igneous_thread"
  "ingredient.ignitedFaebloom|ignited_faebloom"
  "ingredient.illicitHelmlock|illicit_helmlock"
  "ingredient.illicitQuince|illicit_quince"
  "ingredient.illicitTingflower|illicit_tingflower"
  "ingredient.illicitWhitethorn|illicit_whitethorn"
  "ingredient.illicitYarrow|illicit_yarrow"
  "ingredient.illuminatedSpirit|illuminated_spirit"
  "ingredient.illusoryIdol|illusory_idol"
  "ingredient.imageOfALovedOne|image_of_a_loved_one"
  "ingredient.impureNullity|impure_nullity"
  "ingredient.incendiaryAlloy|incendiary_alloy"
  "ingredient.incrementalMappingModule|incremental_mapping_module"
  "ingredient.infectedMass|infected_mass"
  "ingredient.infernalAntifreeze|infernal_antifreeze"
  "ingredient.infernalFlesh|infernal_flesh"
  "ingredient.infusedGold|infused_gold"
  "ingredient.insanityStar|insanity_star"
  "ingredient.inscribedCollar|inscribed_collar"
  "ingredient.insulatedWiring|insulated_wiring"
  "ingredient.intermittenstirrups|intermittenstirrups"
  "ingredient.invertedGrotesque|inverted_grotesque"
  "ingredient.irisdescentElytra|irisdescent_elytra"
  "ingredient.iridescentFortrepace|iridescent_fortrepace"
  "ingredient.ironwoodChips|ironwood_chips"
  "ingredient.ironwoodScale|ironwood_scale"
  "ingredient.ivoryTusk|ivory_tusk"
  "ingredient.ivySprout|ivy_sprout"
  "ingredient.jaggedIcicle|jagged_icicle"
  "ingredient.jaggedRime|jagged_rime"
  "ingredient.jeNeSaisQuoi|je_ne_sais_quoi"
  "ingredient.joltingGeode|jolting_geode"
  "ingredient.kaianScroll|kaian_scroll"
  "ingredient.kaolinClay|kaolin_clay"
  "ingredient.karlJohanCap|karl_johan_cap"
  "ingredient.kerasotSporehead|kerasot_sporehead"
  "ingredient.lacticAcidCrystal|lactic_acid_crystal"
  "ingredient.larbonicSheddings|larbonic_sheddings"
  "ingredient.largeLapis|large_lapis"
  "ingredient.largeTitaniumChunk|large_titanium_chunk"
  "ingredient.larvaeCluster|larvae_cluster"
  "ingredient.laryngealFlesh|laryngeal_flesh"
  "ingredient.lashingHellfire|lashing_hellfire"
  "ingredient.lavaBlisters|lava_blisters"
  "ingredient.leafyStalk|leafy_stalk"
  "ingredient.leather|leather"
  "ingredient.legEaterTooth|leg_eater_tooth"
  "ingredient.leopardBlood|leopard_blood"
  "ingredient.licoriceRopes|licorice_ropes"
  "ingredient.liffLeaf|liff_leaf"
  "ingredient.limestoneCore|limestone_core"
  "ingredient.linearAccelerator|linear_accelerator"
  "ingredient.lintyFiber|linty_fiber"
  "ingredient.lionFang|lion_fang"
  "ingredient.lionHeart|lion_heart"
  "ingredient.lithoflesh|lithoflesh"
  "ingredient.livelyApple|lively_apple"
  "ingredient.lizardScale|lizard_scale"
  "ingredient.lizardTail|lizard_tail"
  "ingredient.lockpickingKit|lockpicking_kit"
  "ingredient.looseAmmunition|loose_ammunition"
  "ingredient.lootedAlloy|looted_alloy"
  "ingredient.lostHeirloom|lost_heirloom"
  "ingredient.lostSpirit|lost_spirit"
  "ingredient.lostTalisman|lost_talisman"
  "ingredient.lotusSeedpod|lotus_seedpod"
  "ingredient.luciolum|luciolum"
  "ingredient.luckyRabbitsFoot|lucky_rabbits_foot"
  "ingredient.luckySpiderEgg|lucky_spider_egg"
  "ingredient.luminescentInk|luminescent_ink"
  "ingredient.luminousRune|luminous_rune"
  "ingredient.lunarCharm|lunar_charm"
  "ingredient.lunarChunk|lunar_chunk"
  "ingredient.lunarDust|lunar_dust"
  "ingredient.lunarShard|lunar_shard"
  "ingredient.luuLuuVertebrae|luu_luu_vertebrae"
  "ingredient.luxicPlasma|luxic_plasma"
  "ingredient.luxrootCuttings|luxroot_cuttings"
  "ingredient.luxuriousSilk|luxurious_silk"
  "ingredient.magicFeather|magic_feather"
  "ingredient.magicalFire|magical_fire"
  "ingredient.magiculeSample|magicule_sample"
  "ingredient.magmaticSkin|magmatic_skin"
  "ingredient.mahoganyHeartwood|mahogany_heartwood"
  "ingredient.majorsBadge|majors_badge"
  "ingredient.malignantNuclei|malignant_nuclei"
  "ingredient.manaExtract|mana_extract"
  "ingredient.mangledSoul|mangled_soul"
  "ingredient.mangledTitaniumScrap|mangled_titanium_scrap"
  "ingredient.mangroveRoot|mangrove_root"
  "ingredient.manisCarapace|manis_carapace"
  "ingredient.manufacturedShortsword|manufactured_shortsword"
  "ingredient.mapleBark|maple_bark"
  "ingredient.marbleStatuette|marble_statuette"
  "ingredient.maroferrous|maroferrous"
  "ingredient.maromagnetite|maromagnetite"
  "ingredient.marrowDust|marrow_dust"
  "ingredient.marsufosaPelt|marsufosa_pelt"
  "ingredient.mashedInsect|mashed_insect"
  "ingredient.mealScraps|meal_scraps"
  "ingredient.megaFern|mega_fern"
  "ingredient.meltedSteel|melted_steel"
  "ingredient.memoryDye|memory_dye"
  "ingredient.metalScraps|metal_scraps"
  "ingredient.mineralCinder|mineral_cinder"
  "ingredient.misprintedNewspaper|misprinted_newspaper"
  "ingredient.mixedJewelDeposit|mixed_jewel_deposit"
  "ingredient.mixedMineralDeposit|mixed_mineral_deposit"
  "ingredient.mixedSeeds|mixed_seeds"
  "ingredient.moldyWrapping|moldy_wrapping"
  "ingredient.moonlightEssence|moonlight_essence"
  "ingredient.mooshroomEar|mooshroom_ear"
  "ingredient.mothAntennae|moth_antennae"
  "ingredient.mountainsHeart|mountains_heart"
  "ingredient.mruck|mruck"
  "ingredient.mucoidMatter|mucoid_matter"
  "ingredient.mulchedDevilWurst|mulched_devil_wurst"
  "ingredient.munchedGrass|munched_grass"
  "ingredient.muralShard|mural_shard"
  "ingredient.muscle|muscle"
  "ingredient.myconidSpores|myconid_spores"
  "ingredient.myocardialLeg|myocardial_leg"
  "ingredient.mysteriousMist|mysterious_mist"
  "ingredient.mythicalHoof|mythical_hoof"
  "ingredient.nagaTail|naga_tail"
  "ingredient.nastyResidue|nasty_residue"
  "ingredient.naturalNitrates|natural_nitrates"
  "ingredient.navalShard|naval_shard"
  "ingredient.navalStone|naval_stone"
  "ingredient.negativeRafflesia|negative_rafflesia"
  "ingredient.neonSeawater|neon_seawater"
  "ingredient.nightmareFuel|nightmare_fuel"
  "ingredient.nobleRibbon|noble_ribbon"
  "ingredient.noseRing|nose_ring"
  "ingredient.novaBloom|nova_bloom"
  "ingredient.obsidianShards|obsidian_shards"
  "ingredient.oceaSteel|ocea_steel"
  "ingredient.oceanicSand|oceanic_sand"
  "ingredient.oceanicSilt|oceanic_silt"
  "ingredient.ocelotPelt|ocelot_pelt"
  "ingredient.ocelotTail|ocelot_tail"
  "ingredient.oddlyUntouchedMarshmallow|oddly_untouched_marshmallow"
  "ingredient.oldBone|old_bone"
  "ingredient.oldExplosives|old_explosives"
  "ingredient.oldTreasure|old_treasure"
  "ingredient.olmicArtifact|olmic_artifact"
  "ingredient.ominousPearl|ominous_pearl"
  "ingredient.opticFiber|optic_fiber"
  "ingredient.opticLens|optic_lens"
  "ingredient.orcEye|orc_eye"
  "ingredient.orcSkin|orc_skin"
  "ingredient.orcTeeth|orc_teeth"
  "ingredient.organicExplosive|organic_explosive"
  "ingredient.ornamentalHorn|ornamental_horn"
  "ingredient.ospreyEgg|osprey_egg"
  "ingredient.ostentatiousCape|ostentatious_cape"
  "ingredient.outdatedNewspaper|outdated_newspaper"
  "ingredient.overgrownBones|overgrown_bones"
  "ingredient.overheatedProcessor|overheated_processor"
  "ingredient.owlFeather|owl_feather"
  "ingredient.pandaKingsCrown|panda_kings_crown"
  "ingredient.paralyzingSpores|paralyzing_spores"
  "ingredient.parasiticAbscission|parasitic_abscission"
  "ingredient.parasiticChitin|parasitic_chitin"
  "ingredient.peacockPlume|peacock_plume"
  "ingredient.pearlescentJewel|pearlescent_jewel"
  "ingredient.pegasusFeather|pegasus_feather"
  "ingredient.penguinEgg|penguin_egg"
  "ingredient.perkishPotato|perkish_potato"
  "ingredient.photophobicKelp|photophobic_kelp"
  "ingredient.phrumkinSeeds|phrumkin_seeds"
  "ingredient.piercingTalons|piercing_talons"
  "ingredient.pigsBlood|pigs_blood"
  "ingredient.pigsRemains|pigs_remains"
  "ingredient.pigmanIvory|pigman_ivory"
  "ingredient.pigmanMeat|pigman_meat"
  "ingredient.pilferedSilver|pilfered_silver"
  "ingredient.pillagedFragment|pillaged_fragment"
  "ingredient.pinkPelulite|pink_pelulite"
  "ingredient.pinkPelute|pink_pelute"
  "ingredient.pinkWool|pink_wool"
  "ingredient.pipistrelleWing|pipistrelle_wing"
  "ingredient.piquantPorkFillet|piquant_pork_fillet"
  "ingredient.piranhaJaw|piranha_jaw"
  "ingredient.pirateBeard|pirate_beard"
  "ingredient.planeOfNonexistence|plane_of_nonexistence"
  "ingredient.plasteelPlating|plasteel_plating"
  "ingredient.platinumGrookEgg|platinum_grook_egg"
  "ingredient.pluckedFeather|plucked_feather"
  "ingredient.pluripotentTissue|pluripotent_tissue"
  "ingredient.plutoniumWaste|plutonium_waste"
  "ingredient.pocketTorch|pocket_torch"
  "ingredient.poisonSac|poison_sac"
  "ingredient.poisonousSpiderEye|poisonous_spider_eye"
  "ingredient.pokeyCactus|pokey_cactus"
  "ingredient.poorlyMadePouch|poorly_made_pouch"
  "ingredient.poppedPustule|popped_pustule"
  "ingredient.portalEmanation|portal_emanation"
  "ingredient.portalRift|portal_rift"
  "ingredient.potato|potato"
  "ingredient.potentVenom|potent_venom"
  "ingredient.powderyBone|powdery_bone"
  "ingredient.prehistoricBread|prehistoric_bread"
  "ingredient.premiumHayBale|premium_hay_bale"
  "ingredient.premiumNectar|premium_nectar"
  "ingredient.preservedRelic|preserved_relic"
  "ingredient.pricklyGrass|prickly_grass"
  "ingredient.primevalSkin|primeval_skin"
  "ingredient.primitiveDelicacy|primitive_delicacy"
  "ingredient.primordialSoul|primordial_soul"
  "ingredient.prismaticSpores|prismatic_spores"
  "ingredient.pristineClaw|pristine_claw"
  "ingredient.pristineLiffLeaf|pristine_liff_leaf"
  "ingredient.prizedFeather|prized_feather"
  "ingredient.prizedPelt|prized_pelt"
  "ingredient.protectiveFabric|protective_fabric"
  "ingredient.psionicQuill|psionic_quill"
  "ingredient.pureQuartz|pure_quartz"
  "ingredient.pureRainStone|pure_rain_stone"
  "ingredient.purestTear|purest_tear"
  "ingredient.putridGunk|putrid_gunk"
  "ingredient.putridSpores|putrid_spores"
  "ingredient.pykrete|pykrete"
  "ingredient.qualityStackpeakEgg|quality_stackpeak_egg"
  "ingredient.quartzCluster|quartz_cluster"
  "ingredient.queenBeeStinger|queen_bee_stinger"
  "ingredient.quickClaw|quick_claw"
  "ingredient.rabbitCarcass|rabbit_carcass"
  "ingredient.raccoonTail|raccoon_tail"
  "ingredient.radiantSeeds|radiant_seeds"
  "ingredient.radioactiveSoil|radioactive_soil"
  "ingredient.rancidFlesh|rancid_flesh"
  "ingredient.rapidFireMechanism|rapid_fire_mechanism"
  "ingredient.rarePotato|rare_potato"
  "ingredient.ratHair|rat_hair"
  "ingredient.razorSharpTooth|razor_sharp_tooth"
  "ingredient.recluseVenomSac|recluse_venom_sac"
  "ingredient.redCrystalDust|red_crystal_dust"
  "ingredient.redMercury|red_mercury"
  "ingredient.redMushroom|red_mushroom"
  "ingredient.redScale|red_scale"
  "ingredient.redShale|red_shale"
  "ingredient.regenerativePins|regenerative_pins"
  "ingredient.regretlessTalisman|regretless_talisman"
  "ingredient.reinforcedLeather|reinforced_leather"
  "ingredient.reishiMushroom|reishi_mushroom"
  "ingredient.rejectedGeode|rejected_geode"
  "ingredient.relicOfTheFuture|relic_of_the_future"
  "ingredient.relicOfThePast|relic_of_the_past"
  "ingredient.remedialPaste|remedial_paste"
  "ingredient.repairToolkit|repair_toolkit"
  "ingredient.reptileScales|reptile_scales"
  "ingredient.residualSpirit|residual_spirit"
  "ingredient.resilientStone|resilient_stone"
  "ingredient.resistantStrain|resistant_strain"
  "ingredient.retinalBarbs|retinal_barbs"
  "ingredient.retinalMembrane|retinal_membrane"
  "ingredient.rigidFin|rigid_fin"
  "ingredient.ripeAureateFruit|ripe_aureate_fruit"
  "ingredient.ritualCatalyst|ritual_catalyst"
  "ingredient.riverClay|river_clay"
  "ingredient.roastedTissue|roasted_tissue"
  "ingredient.robotAntenna|robot_antenna"
  "ingredient.rockHardBeak|rock_hard_beak"
  "ingredient.rockyMind|rocky_mind"
  "ingredient.rockySpirit|rocky_spirit"
  "ingredient.rootsOfEternity|roots_of_eternity"
  "ingredient.rose|rose"
  "ingredient.rototilledSoil|rototilled_soil"
  "ingredient.rottenBone|rotten_bone"
  "ingredient.rottenFlesh|rotten_flesh"
  "ingredient.rottenTeeth|rotten_teeth"
  "ingredient.rottingBandage|rotting_bandage"
  "ingredient.rottingBone|rotting_bone"
  "ingredient.routerShield|router_shield"
  "ingredient.royalBugsBlood|royal_bugs_blood"
  "ingredient.ruinsShard|ruins_shard"
  "ingredient.runnersBandages|runners_bandages"
  "ingredient.rustedOperatingScissors|rusted_operating_scissors"
  "ingredient.rustyAxeHead|rusty_axe_head"
  "ingredient.rustySpurs|rusty_spurs"
  "ingredient.salt|salt"
  "ingredient.saltWater|salt_water"
  "ingredient.saltedSalmon|salted_salmon"
  "ingredient.saltpetre|saltpetre"
  "ingredient.sanctifiedSheepSoul|sanctified_sheep_soul"
  "ingredient.sandyBonemeal|sandy_bonemeal"
  "ingredient.sandyLoam|sandy_loam"
  "ingredient.savannahStone|savannah_stone"
  "ingredient.scaldingSand|scalding_sand"
  "ingredient.scarabHusk|scarab_husk"
  "ingredient.scarredLeather|scarred_leather"
  "ingredient.scopaesthesia|scopaesthesia"
  "ingredient.scorchingHorn|scorching_horn"
  "ingredient.scoriaPollen|scoria_pollen"
  "ingredient.scuttlingSyenite|scuttling_syenite"
  "ingredient.seaSalt|sea_salt"
  "ingredient.seabirdEgg|seabird_egg"
  "ingredient.seabirdFeather|seabird_feather"
  "ingredient.seagrass|seagrass"
  "ingredient.sealedBlaze|sealed_blaze"
  "ingredient.secretHerb|secret_herb"
  "ingredient.sentientLeukocyte|sentient_leukocyte"
  "ingredient.sentientMagmaticGem|sentient_magmatic_gem"
  "ingredient.sentientShadow|sentient_shadow"
  "ingredient.sentientSlimeball|sentient_slimeball"
  "ingredient.sentientWater|sentient_water"
  "ingredient.serafite|serafite"
  "ingredient.serpentTongue|serpent_tongue"
  "ingredient.serpentsFang|serpents_fang"
  "ingredient.serratedCanine|serrated_canine"
  "ingredient.severedHeart|severed_heart"
  "ingredient.severedLeg|severed_leg"
  "ingredient.shadowOfRuin|shadow_of_ruin"
  "ingredient.sharpClaw|sharp_claw"
  "ingredient.sharpEdge|sharp_edge"
  "ingredient.sharpeningStone|sharpening_stone"
  "ingredient.sharperClaw|sharper_claw"
  "ingredient.shatteredAmmunition|shattered_ammunition"
  "ingredient.shatteredBlade|shattered_blade"
  "ingredient.shatteredDawnlight|shattered_dawnlight"
  "ingredient.shatteredMemoryShard|shattered_memory_shard"
  "ingredient.sheepHoof|sheep_hoof"
  "ingredient.shimmeringJewel|shimmering_jewel"
  "ingredient.shinestingScorpionTail|shinesting_scorpion_tail"
  "ingredient.shiningWool|shining_wool"
  "ingredient.shinyGravel|shiny_gravel"
  "ingredient.shinyMineralDeposit|shiny_mineral_deposit"
  "ingredient.shinyPebble|shiny_pebble"
  "ingredient.shortingWire|shorting_wire"
  "ingredient.shreddedBone|shredded_bone"
  "ingredient.silverBullet|silver_bullet"
  "ingredient.silverFeather|silver_feather"
  "ingredient.skeletonKey|skeleton_key"
  "ingredient.skyFlux|sky_flux"
  "ingredient.skySnailShell|sky_snail_shell"
  "ingredient.skyboundRemnant|skybound_remnant"
  "ingredient.skyraiderCoin|skyraider_coin"
  "ingredient.slateSheet|slate_sheet"
  "ingredient.slimySkin|slimy_skin"
  "ingredient.slipperyMuscle|slippery_muscle"
  "ingredient.sliverOfSunrise|sliver_of_sunrise"
  "ingredient.sludgeParasite|sludge_parasite"
  "ingredient.sluggishSubstance|sluggish_substance"
  "ingredient.smokeBomb|smoke_bomb"
  "ingredient.smoothSilt|smooth_silt"
  "ingredient.snakeEye|snake_eye"
  "ingredient.snakeScale|snake_scale"
  "ingredient.snakeSkin|snake_skin"
  "ingredient.snakeTooth|snake_tooth"
  "ingredient.snowClump|snow_clump"
  "ingredient.snowHeart|snow_heart"
  "ingredient.soapstone|soapstone"
  "ingredient.softBlueWool|soft_blue_wool"
  "ingredient.softGreenWool|soft_green_wool"
  "ingredient.softRedWool|soft_red_wool"
  "ingredient.softSand|soft_sand"
  "ingredient.softSilk|soft_silk"
  "ingredient.softWhiteWool|soft_white_wool"
  "ingredient.softYellowWool|soft_yellow_wool"
  "ingredient.soggyStone|soggy_stone"
  "ingredient.soulcrystalHorn|soulcrystal_horn"
  "ingredient.soldierRations|soldier_rations"
  "ingredient.solidUltravioletRay|solid_ultraviolet_ray"
  "ingredient.soughtAfterOre|sought_after_ore"
  "ingredient.soulAmalgamate|soul_amalgamate"
  "ingredient.soulEssence|soul_essence"
  "ingredient.soulStone|soul_stone"
  "ingredient.soulboundCinders|soulbound_cinders"
  "ingredient.soulfireMatterweave|soulfire_matterweave"
  "ingredient.sparkOfTheOasis|spark_of_the_oasis"
  "ingredient.spectralHorns|spectral_horns"
  "ingredient.spectralSpike|spectral_spike"
  "ingredient.spellboundAsh|spellbound_ash"
  "ingredient.sphagnumMoss|sphagnum_moss"
  "ingredient.spiderEggs|spider_eggs"
  "ingredient.spiderFang|spider_fang"
  "ingredient.spiderLeg|spider_leg"
  "ingredient.spikedResidue|spiked_residue"
  "ingredient.spikedCapsule|spiked_capsule"
  "ingredient.spikyVine|spiky_vine"
  "ingredient.spirographTablet|spirograph_tablet"
  "ingredient.splinteredGreathammer|splintered_greathammer"
  "ingredient.splitEssence|split_essence"
  "ingredient.spreadingFireweed|spreading_fireweed"
  "ingredient.squidBeak|squid_beak"
  "ingredient.squidBrain|squid_brain"
  "ingredient.squidInk|squid_ink"
  "ingredient.stackOfCoins|stack_of_coins"
  "ingredient.stackpeakEgg|stackpeak_egg"
  "ingredient.stackpeakPlumage|stackpeak_plumage"
  "ingredient.staleBread|stale_bread"
  "ingredient.stickyFern|sticky_fern"
  "ingredient.stickyMudball|sticky_mudball"
  "ingredient.stolenBurnmilk|stolen_burnmilk"
  "ingredient.stolenEgg|stolen_egg"
  "ingredient.stolenGoods|stolen_goods"
  "ingredient.stolenHarvest|stolen_harvest"
  "ingredient.stolenHeirloom|stolen_heirloom"
  "ingredient.stolenPearls|stolen_pearls"
  "ingredient.stolenSeeds|stolen_seeds"
  "ingredient.stonePlating|stone_plating"
  "ingredient.stonewalkerCore|stonewalker_core"
  "ingredient.stormHorn|storm_horn"
  "ingredient.strangeGeode|strange_geode"
  "ingredient.strangeTrinket|strange_trinket"
  "ingredient.stretchedRawhide|stretched_rawhide"
  "ingredient.strongFlesh|strong_flesh"
  "ingredient.sturdyFlesh|sturdy_flesh"
  "ingredient.subjoinedBrain|subjoined_brain"
  "ingredient.subsumingDarkness|subsuming_darkness"
  "ingredient.succulentCrabMeat|succulent_crab_meat"
  "ingredient.sugarStick|sugar_stick"
  "ingredient.sunStainedSkin|sun_stained_skin"
  "ingredient.sunkenScales|sunken_scales"
  "ingredient.suspiciousMixture|suspicious_mixture"
  "ingredient.suspiciousShrubs|suspicious_shrubs"
  "ingredient.swooperWing|swooper_wing"
  "ingredient.sylphidTears|sylphid_tears"
  "ingredient.tackyGoop|tacky_goop"
  "ingredient.tailoredGarments|tailored_garments"
  "ingredient.tangyNectar|tangy_nectar"
  "ingredient.tannedFlesh|tanned_flesh"
  "ingredient.tarnishedGoldFoil|tarnished_gold_foil"
  "ingredient.tatteredMagicCloth|tattered_magic_cloth"
  "ingredient.teaTreeMushroom|tea_tree_mushroom"
  "ingredient.tenderPorkFillet|tender_pork_fillet"
  "ingredient.tendonClump|tendon_clump"
  "ingredient.tenebrousPlasma|tenebrous_plasma"
  "ingredient.tentacle|tentacle"
  "ingredient.terraSteel|terra_steel"
  "ingredient.terracottaChunk|terracotta_chunk"
  "ingredient.terramarineDust|terramarine_dust"
  "ingredient.theGrootslangsHeart|the_grootslangs_heart"
  "ingredient.thercksChain|thercks_chain"
  "ingredient.thermalReplication|thermal_replication"
  "ingredient.thickMud|thick_mud"
  "ingredient.thickVines|thick_vines"
  "ingredient.thinQuill|thin_quill"
  "ingredient.thornedTusk|thorned_tusk"
  "ingredient.thornyShoot|thorny_shoot"
  "ingredient.throbbingAvosHeart|throbbing_avos_heart"
  "ingredient.titanicTail|titanic_tail"
  "ingredient.titaniumChunk|titanium_chunk"
  "ingredient.tornFabric|torn_fabric"
  "ingredient.tornRawhide|torn_rawhide"
  "ingredient.tornSkin|torn_skin"
  "ingredient.toughBone|tough_bone"
  "ingredient.toughSkin|tough_skin"
  "ingredient.toxicLumps|toxic_lumps"
  "ingredient.toxicSpores|toxic_spores"
  "ingredient.toxxulousRipperLegs|toxxulous_ripper_legs"
  "ingredient.transformativity|transformativity"
  "ingredient.tribalTome|tribal_tome"
  "ingredient.trollHair|troll_hair"
  "ingredient.tropicalHoneysuckle|tropical_honeysuckle"
  "ingredient.truffle|truffle"
  "ingredient.tungstenChunk|tungsten_chunk"
  "ingredient.turtleShell|turtle_shell"
  "ingredient.twistedCoral|twisted_coral"
  "ingredient.twistedOrgan|twisted_organ"
  "ingredient.ultramarineMinnow|ultramarine_minnow"
  "ingredient.undeadHeart|undead_heart"
  "ingredient.undiscoveredPlant|undiscovered_plant"
  "ingredient.unholySpirit|unholy_spirit"
  "ingredient.unholyWater|unholy_water"
  "ingredient.unicornHorn|unicorn_horn"
  "ingredient.unmeltableIce|unmeltable_ice"
  "ingredient.unsettlingSoul|unsettling_soul"
  "ingredient.ursineClaw|ursine_claw"
  "ingredient.usedFireball|used_fireball"
  "ingredient.venomTippedBolt|venom_tipped_bolt"
  "ingredient.vikingStone|viking_stone"
  "ingredient.vileStone|vile_stone"
  "ingredient.vimVeins|vim_veins"
  "ingredient.viralTentacle|viral_tentacle"
  "ingredient.viscousSlime|viscous_slime"
  "ingredient.vistaMist|vista_mist"
  "ingredient.voidEssence|void_essence"
  "ingredient.voidParticulates|void_particulates"
  "ingredient.voidstoneSample|voidstone_sample"
  "ingredient.voidtossedMemory|voidtossed_memory"
  "ingredient.volatileLight|volatile_light"
  "ingredient.volatileMatter|volatile_matter"
  "ingredient.vortexExpulsion|vortex_expulsion"
  "ingredient.warmHide|warm_hide"
  "ingredient.warmParka|warm_parka"
  "ingredient.warpedSkin|warped_skin"
  "ingredient.waterDropwort|water_dropwort"
  "ingredient.waterfallThyme|waterfall_thyme"
  "ingredient.waterloggedBranch|waterlogged_branch"
  "ingredient.wateryAura|watery_aura"
  "ingredient.weakeningCatalyst|weakening_catalyst"
  "ingredient.weatheredIdol|weathered_idol"
  "ingredient.webbedOffshoot|webbed_offshoot"
  "ingredient.wendigoBone|wendigo_bone"
  "ingredient.werewolfTail|werewolf_tail"
  "ingredient.windOrnament|wind_ornament"
  "ingredient.windsweptRoots|windswept_roots"
  "ingredient.windyAura|windy_aura"
  "ingredient.wingedHelmet|winged_helmet"
  "ingredient.wingsArmourFragment|wings_armour_fragment"
  "ingredient.witheredRoot|withered_root"
  "ingredient.wolfFang|wolf_fang"
  "ingredient.woodScrap|wood_scrap"
  "ingredient.woodShavings|wood_shavings"
  "ingredient.woodSnippet|wood_snippet"
  "ingredient.wool|wool"
  "ingredient.woolyArmour|wooly_armour"
  "ingredient.worldIlluminator|world_illuminator"
  "ingredient.wormSign|worm_sign"
  "ingredient.wornCoin|worn_coin"
  "ingredient.wornMemorabilia|worn_memorabilia"
  "ingredient.wrathfulCatalyst|wrathful_catalyst"
  "ingredient.wrigglingDarkness|wriggling_darkness"
  "ingredient.wrigglingWoodenArm|wriggling_wooden_arm"
  "ingredient.wybelFluff|wybel_fluff"
  "ingredient.wybelTaffy|wybel_taffy"
  "ingredient.yetiFur|yeti_fur"
  "ingredient.youngCheese|young_cheese"
  "ingredient.zealousIlluminator|zealous_illuminator"
  "ingredient.zhightCoralPiece|zhight_coral_piece"
  "ingredient.zhightHerbalMix|zhight_herbal_mix"
  "ingredient.zhightShinyStone|zhight_shiny_stone"
  "ingredient.zhightWeirdMagicRock|zhight_weird_magic_rock"
  "ingredient.zombieBrain|zombie_brain"
  "ingredient.zombieEye|zombie_eye"
)

LOOKUPS_MATERIALS=(
  "profession.ingotCopper|mining/ingot_copper"
  "profession.gemCopper|mining/gem_copper"
  "profession.ingotGranite|mining/ingot_granite"
  "profession.gemGranite|mining/gem_granite"
  "profession.ingotGold|mining/ingot_gold"
  "profession.gemGold|mining/gem_gold"
  "profession.ingotSandstone|mining/ingot_sandstone"
  "profession.gemSandstone|mining/gem_sandstone"
  "profession.ingotIron|mining/ingot_iron"
  "profession.gemIron|mining/gem_iron"
  "profession.ingotSilver|mining/ingot_silver"
  "profession.gemSilver|mining/gem_silver"
  "profession.ingotCobalt|mining/ingot_cobalt"
  "profession.gemCobalt|mining/gem_cobalt"
  "profession.ingotKanderstone|mining/ingot_kanderstone"
  "profession.gemKanderstone|mining/gem_kander"
  "profession.ingotDiamond|mining/ingot_diamond"
  "profession.gemDiamond|mining/gem_diamond"
  "profession.ingotMolten|mining/ingot_molten"
  "profession.gemMolten|mining/gem_molten"
  "profession.ingotVoidstone|mining/ingot_void"
  "profession.gemVoidstone|mining/gem_void"
  "profession.ingotDernic|mining/ingot_dernic"
  "profession.gemDernic|mining/gem_dernic"
  "profession.ingotTitanium|mining/ingot_titanium"
  "profession.gemTitanium|mining/gem_titanium"
  "profession.ingotCinnabar|mining/ingot_cinnabar"
  "profession.gemCinnabar|mining/gem_cinnabar"
  "profession.plankOak|woodcutting/plank_oak"
  "profession.paperOak|woodcutting/paper_oak"
  "profession.plankBirch|woodcutting/plank_birch"
  "profession.paperBirch|woodcutting/paper_birch"
  "profession.plankWillow|woodcutting/plank_willow"
  "profession.paperWillow|woodcutting/paper_willow"
  "profession.plankAcacia|woodcutting/plank_acacia"
  "profession.paperAcacia|woodcutting/paper_acacia"
  "profession.plankSpruce|woodcutting/plank_spruce"
  "profession.paperSpruce|woodcutting/paper_spruce"
  "profession.plankJungle|woodcutting/plank_jungle"
  "profession.paperJungle|woodcutting/paper_jungle"
  "profession.plankDark|woodcutting/plank_dark"
  "profession.paperDark|woodcutting/paper_dark"
  "profession.plankLight|woodcutting/plank_light"
  "profession.paperLight|woodcutting/paper_light"
  "profession.plankPine|woodcutting/plank_pine"
  "profession.paperPine|woodcutting/paper_pine"
  "profession.plankAvo|woodcutting/plank_avo"
  "profession.paperAvo|woodcutting/paper_avo"
  "profession.plankSky|woodcutting/plank_sky"
  "profession.paperSky|woodcutting/paper_sky"
  "profession.plankDernic|woodcutting/plank_dernic"
  "profession.paperDernic|woodcutting/paper_dernic"
  "profession.plankMaple|woodcutting/plank_maple"
  "profession.paperMaple|woodcutting/paper_maple"
  "profession.plankRedwood|woodcutting/plank_redwood"
  "profession.paperRedwood|woodcutting/paper_redwood"
  "profession.stringWheat|farming/string_wheat"
  "profession.grainWheat|farming/grain_wheat"
  "profession.stringBarley|farming/string_barley"
  "profession.grainBarley|farming/grain_barley"
  "profession.stringOat|farming/string_oat"
  "profession.grainOat|farming/grain_oat"
  "profession.stringMalt|farming/string_malt"
  "profession.grainMalt|farming/grain_malt"
  "profession.stringHops|farming/string_hops"
  "profession.grainHops|farming/grain_hops"
  "profession.stringRye|farming/string_rye"
  "profession.grainRye|farming/grain_rye"
  "profession.stringMillet|farming/string_millet"
  "profession.grainMillet|farming/grain_millet"
  "profession.stringDecay|farming/string_decay"
  "profession.grainDecay|farming/grain_decay"
  "profession.stringRice|farming/string_rice"
  "profession.grainRice|farming/grain_rice"
  "profession.stringSorghum|farming/string_sorghum"
  "profession.grainSorghum|farming/grain_sorghum"
  "profession.stringHemp|farming/string_hemp"
  "profession.grainHemp|farming/grain_hemp"
  "profession.stringDernic|farming/string_dernic"
  "profession.grainDernic|farming/grain_dernic"
  "profession.stringJute|farming/string_jute"
  "profession.grainJute|farming/grain_jute"
  "profession.stringHeather|farming/string_heather"
  "profession.grainHeather|farming/grain_heather"
  "profession.oilGudgeon|fishing/oil_gudgeon"
  "profession.meatGudgeon|fishing/meat_gudgeon"
  "profession.oilTrout|fishing/oil_trout"
  "profession.meatTrout|fishing/meat_trout"
  "profession.oilSalmon|fishing/oil_salmon"
  "profession.meatSalmon|fishing/meat_salmon"
  "profession.oilCarp|fishing/oil_carp"
  "profession.meatCarp|fishing/meat_carp"
  "profession.oilIcefish|fishing/oil_ice"
  "profession.meatIcefish|fishing/meat_ice"
  "profession.oilPiranha|fishing/oil_piranha"
  "profession.meatPiranha|fishing/meat_piranha"
  "profession.oilKoi|fishing/oil_koi"
  "profession.meatKoi|fishing/meat_koi"
  "profession.oilGylia|fishing/oil_gylia"
  "profession.meatGylia|fishing/meat_gylia"
  "profession.oilBass|fishing/oil_bass"
  "profession.meatBass|fishing/meat_bass"
  "profession.oilMolten|fishing/oil_molten"
  "profession.meatMolten|fishing/meat_molten"
  "profession.oilStarfish|fishing/oil_star"
  "profession.meatStarfish|fishing/meat_star"
  "profession.oilDernic|fishing/oil_dernic"
  "profession.meatDernic|fishing/meat_dernic"
  "profession.oilSturgeon|fishing/oil_sturgeon"
  "profession.meatSturgeon|fishing/meat_sturgeon"
  "profession.oilMahseer|fishing/oil_mahseer"
  "profession.meatMahseer|fishing/meat_mahseer"
)
  
LOOKUPS_TOOLS=(
  "wooden_pickaxe|wooden_pickaxe"
  "wooden_axe|wooden_axe"
  "wooden_scythe|wooden_scythe"
  "wooden_rod|wooden_rod"
  "stone_pickaxe|stone_pickaxe"
  "stone_axe|stone_axe"
  "stone_scythe|stone_scythe"
  "stone_rod|stone_rod"
  "copper_pickaxe|copper_pickaxe"
  "copper_axe|copper_axe"
  "copper_scythe|copper_scythe"
  "copper_rod|copper_rod"
  "bronze_pickaxe|bronze_pickaxe"
  "bronze_axe|bronze_axe"
  "bronze_scythe|bronze_scythe"
  "bronze_rod|bronze_rod"
  "golden_pickaxe|golden_pickaxe"
  "golden_axe|golden_axe"
  "golden_scythe|golden_scythe"
  "golden_rod|golden_rod"
  "iron_pickaxe|iron_pickaxe"
  "iron_axe|iron_axe"
  "iron_scythe|iron_scythe"
  "iron_rod|iron_rod"
  "steel_pickaxe|steel_pickaxe"
  "steel_axe|steel_axe"
  "steel_scythe|steel_scythe"
  "steel_rod|steel_rod"
  "cobalt_pickaxe|cobalt_pickaxe"
  "cobalt_axe|cobalt_axe"
  "cobalt_scythe|cobalt_scythe"
  "cobalt_rod|cobalt_rod"
  "diamond_pickaxe|diamond_pickaxe"
  "diamond_axe|diamond_axe"
  "diamond_scythe|diamond_scythe"
  "diamond_rod|diamond_rod"
  "molten_pickaxe|molten_pickaxe"
  "molten_axe|molten_axe"
  "molten_scythe|molten_scythe"
  "molten_rod|molten_rod"
  "void_pickaxe|void_pickaxe"
  "void_axe|void_axe"
  "void_scythe|void_scythe"
  "void_rod|void_rod"
  "dernic_pickaxe|dernic_pickaxe"
  "dernic_axe|dernic_axe"
  "dernic_scythe|dernic_scythe"
  "dernic_rod|dernic_rod"
  "titanium_pickaxe|titanium_pickaxe"
  "titanium_axe|titanium_axe"
  "titanium_scythe|titanium_scythe"
  "titanium_rod|titanium_rod"
)

LOOKUPS_MISC=(
  "mythic_box|loot/mythic"
  "beacon_color|gui/beacon/white|range"
  "corkian_amplifier|augment/corkian_amplifier"
  "corkian_insulator|augment/corkian_insulator"
  "corkian_simulator|augment/corkian_simulator"
  "dungeon_key|dungeon/key"
  "dungeon_key_broken|dungeon/key_broken"
  "rune_az|rune/az"
  "rune_nii|rune/nii"
  "rune_uth|rune/uth"
  "rune_tol|rune/tol"
  "rune_ek|rune/ek"
  "ward_black|ward/black"
  "ward_blue|ward/blue"
  "ward_cyan|ward/cyan"
  "ward_green|ward/green"
  "ward_orange|ward/orange"
  "ward_pink|ward/pink"
  "ward_purple|ward/purple"
  "ward_red|ward/red"
  "ward_white|ward/white"
  "ward_yellow|ward/yellow"
  "default_arrow_down|gui/button/arrow_down_default"
  "default_arrow_up|gui/button/arrow_up_default"
  "tome|mastery_tome|range"
  "charm|charm|range"
  "ring|accessory/ring|range"
  "bracelet|accessory/bracelet|range"
  "necklace|accessory/necklace|range"
  "bow|weapon/archer,skin/bow|range"
  "dagger|weapon/assassin,skin/dagger|range"
  "wand|weapon/mage,skin/wand|range"
  "relik|weapon/shaman,skin/relik|range"
  "spear|weapon/warrior,skin/spear|range"
  "helmet_skin|skin/hat|range"
)

# U = Up
# D = Down
# L = Left
# R = Right
# For the three way the direction in the name is the middle part.
# Multi-direction combos are ordered U, R, D, L.
LOOKUPS_ABILITY_TREE=(
  "abilityTree.aspectArcher|aspect/archer"
  "abilityTree.aspectAssassin|aspect/assassin"
  "abilityTree.aspectMage|aspect/mage"
  "abilityTree.aspectShaman|aspect/shaman"
  "abilityTree.aspectWarrior|aspect/warrior"

  "abilityTree.archetypeBoltslinger|archetype/archer/boltslinger"
  "abilityTree.archetypeSharpshooter|archetype/archer/sharpshooter"
  "abilityTree.archetypeTrapper|archetype/archer/trapper"
  "abilityTree.archetypeAcrobat|archetype/assassin/acrobat"
  "abilityTree.archetypeShadestepper|archetype/assassin/shadestepper"
  "abilityTree.archetypeTrickster|archetype/assassin/trickster"
  "abilityTree.archetypeArcanist|archetype/mage/arcanist"
  "abilityTree.archetypeLightbender|archetype/mage/lightbender"
  "abilityTree.archetypeRiftwalker|archetype/mage/riftwalker"
  "abilityTree.archetypeAcolyte|archetype/shaman/acolyte"
  "abilityTree.archetypeRitualist|archetype/shaman/ritualist"
  "abilityTree.archetypeSummoner|archetype/shaman/summoner"
  "abilityTree.archetypeBattleMonk|archetype/warrior/battle_monk"
  "abilityTree.archetypeFallen|archetype/warrior/fallen"
  "abilityTree.archetypePaladin|archetype/warrior/paladin"

  #ability tree branches
  "abilityTree.branchFourWay|branch/0"
  "abilityTree.branchFourWayActiveURDL|branch/0_active_0"
  "abilityTree.branchFourWayActiveURL|branch/0_active_1"
  "abilityTree.branchFourWayActiveURD|branch/0_active_2"
  "abilityTree.branchFourWayActiveRDL|branch/0_active_3"
  "abilityTree.branchFourWayActiveUDL|branch/0_active_4"
  "abilityTree.branchFourWayActiveUL|branch/0_active_5"
  "abilityTree.branchFourWayActiveUR|branch/0_active_6"
  "abilityTree.branchFourWayActiveRD|branch/0_active_7"
  "abilityTree.branchFourWayActiveDL|branch/0_active_8"
  "abilityTree.branchFourWayActiveUD|branch/0_active_9"
  "abilityTree.branchFourWayActiveRL|branch/0_active_10"
  "abilityTree.branchThreeWayUp|branch/1"
  "abilityTree.branchThreeWayUpActiveURL|branch/1_active_0"
  "abilityTree.branchThreeWayUpActiveUL|branch/1_active_1"
  "abilityTree.branchThreeWayUpActiveUR|branch/1_active_2"
  "abilityTree.branchThreeWayUpActiveRL|branch/1_active_3"
  "abilityTree.branchThreeWayRight|branch/2"
  "abilityTree.branchThreeWayRightActiveURD|branch/2_active_0"
  "abilityTree.branchThreeWayRightActiveUR|branch/2_active_1"
  "abilityTree.branchThreeWayRightActiveRD|branch/2_active_2"
  "abilityTree.branchThreeWayRightActiveUD|branch/2_active_3"
  "abilityTree.branchThreeWayDown|branch/3"
  "abilityTree.branchThreeWayDownActiveRDL|branch/3_active_0"
  "abilityTree.branchThreeWayDownActiveDL|branch/3_active_1"
  "abilityTree.branchThreeWayDownActiveRD|branch/3_active_2"
  "abilityTree.branchThreeWayDownActiveRL|branch/3_active_3"
  "abilityTree.branchThreeWayLeft|branch/4"
  "abilityTree.branchThreeWayLeftActiveUDL|branch/4_active_0"
  "abilityTree.branchThreeWayLeftActiveDL|branch/4_active_1"
  "abilityTree.branchThreeWayLeftActiveUL|branch/4_active_2"
  "abilityTree.branchThreeWayLeftActiveUD|branch/4_active_3"
  "abilityTree.branchUpLeftTurn|branch/5"
  "abilityTree.branchUpLeftTurnActiveUL|branch/5_active_0"
  "abilityTree.branchUpRightTurn|branch/6"
  "abilityTree.branchUpRightTurnActiveUR|branch/6_active_0"
  "abilityTree.branchDownRightTurn|branch/7"
  "abilityTree.branchDownRightTurnActiveRD|branch/7_active_0"
  "abilityTree.branchDownLeftTurn|branch/8"
  "abilityTree.branchDownLeftTurnActiveDL|branch/8_active_0"
  "abilityTree.branchVertical|branch/9"
  "abilityTree.branchVerticalActiveUD|branch/9_active_0"
  "abilityTree.branchHorizontal|branch/10"
  "abilityTree.branchHorizontalActiveRL|branch/10_active_0"

  #archer
  "abilityTree.archerAbilityLocked|node/archer"
  "abilityTree.archerAbilityUnlockable|node/archer_available"
  "abilityTree.archerAbilityUnlocked|node/archer_selected"

  "abilityTree.boltslingerUltimateLocked|ultimate/boltslinger"
  "abilityTree.boltslingerUltimateUnlockable|ultimate/boltslinger_available"
  "abilityTree.boltslingerUltimateBlocked|ultimate/boltslinger_disabled"
  "abilityTree.boltslingerUltimateUnlocked|ultimate/boltslinger_selected"

  "abilityTree.trapperUltimateLocked|ultimate/trapper"
  "abilityTree.trapperUltimateUnlockable|ultimate/trapper_available"
  "abilityTree.trapperUltimateBlocked|ultimate/trapper_disabled"
  "abilityTree.trapperUltimateUnlocked|ultimate/trapper_selected"

  "abilityTree.sharpshooterUltimateLocked|ultimate/sharpshooter"
  "abilityTree.sharpshooterUltimateUnlockable|ultimate/sharpshooter_available"
  "abilityTree.sharpshooterUltimateBlocked|ultimate/sharpshooter_disabled"
  "abilityTree.sharpshooterUltimateUnlocked|ultimate/sharpshooter_selected"

  #assassin
  "abilityTree.assassinAbilityLocked|node/assassin"
  "abilityTree.assassinAbilityUnlockable|node/assassin_available"
  "abilityTree.assassinAbilityUnlocked|node/assassin_selected"

  "abilityTree.shadestepperUltimateLocked|ultimate/shadestepper"
  "abilityTree.shadestepperUltimateUnlockable|ultimate/shadestepper_available"
  "abilityTree.shadestepperUltimateBlocked|ultimate/shadestepper_disabled"
  "abilityTree.shadestepperUltimateUnlocked|ultimate/shadestepper_selected"

  "abilityTree.tricksterUltimateLocked|ultimate/trickster"
  "abilityTree.tricksterUltimateUnlockable|ultimate/trickster_available"
  "abilityTree.tricksterUltimateBlocked|ultimate/trickster_disabled"
  "abilityTree.tricksterUltimateUnlocked|ultimate/trickster_selected"

  "abilityTree.acrobatUltimateLocked|ultimate/acrobat"
  "abilityTree.acrobatUltimateUnlockable|ultimate/acrobat_available"
  "abilityTree.acrobatUltimateBlocked|ultimate/acrobat_disabled"
  "abilityTree.acrobatUltimateUnlocked|ultimate/acrobat_selected"

  #mage
  "abilityTree.mageAbilityLocked|node/mage"
  "abilityTree.mageAbilityUnlockable|node/mage_available"
  "abilityTree.mageAbilityUnlocked|node/mage_selected"

  "abilityTree.lightbenderUltimateLocked|ultimate/light_bender"
  "abilityTree.lightbenderUltimateUnlockable|ultimate/light_bender_available"
  "abilityTree.lightbenderUltimateBlocked|ultimate/light_bender_disabled"
  "abilityTree.lightbenderUltimateUnlocked|ultimate/light_bender_selected"

  "abilityTree.riftwalkerUltimateLocked|ultimate/riftwalker"
  "abilityTree.riftwalkerUltimateUnlockable|ultimate/riftwalker_available"
  "abilityTree.riftwalkerUltimateBlocked|ultimate/riftwalker_disabled"
  "abilityTree.riftwalkerUltimateUnlocked|ultimate/riftwalker_selected"

  "abilityTree.arcanistUltimateLocked|ultimate/arcanist"
  "abilityTree.arcanistUltimateUnlockable|ultimate/arcanist_available"
  "abilityTree.arcanistUltimateBlocked|ultimate/arcanist_disabled"
  "abilityTree.arcanistUltimateUnlocked|ultimate/arcanist_selected"

  #shaman
  "abilityTree.shamanAbilityLocked|node/shaman"
  "abilityTree.shamanAbilityUnlockable|node/shaman_available"
  "abilityTree.shamanAbilityUnlocked|node/shaman_selected"

  "abilityTree.summonerUltimateLocked|ultimate/summoner"
  "abilityTree.summonerUltimateUnlockable|ultimate/summoner_available"
  "abilityTree.summonerUltimateBlocked|ultimate/summoner_disabled"
  "abilityTree.summonerUltimateUnlocked|ultimate/summoner_selected"

  "abilityTree.ritualistUltimateLocked|ultimate/ritualist"
  "abilityTree.ritualistUltimateUnlockable|ultimate/ritualist_available"
  "abilityTree.ritualistUltimateBlocked|ultimate/ritualist_disabled"
  "abilityTree.ritualistUltimateUnlocked|ultimate/ritualist_selected"

  "abilityTree.acolyteUltimateLocked|ultimate/acolyte"
  "abilityTree.acolyteUltimateUnlockable|ultimate/acolyte_available"
  "abilityTree.acolyteUltimateBlocked|ultimate/acolyte_disabled"
  "abilityTree.acolyteUltimateUnlocked|ultimate/acolyte_selected"

  #warrior
  "abilityTree.warriorAbilityLocked|node/warrior"
  "abilityTree.warriorAbilityUnlockable|node/warrior_available"
  "abilityTree.warriorAbilityUnlocked|node/warrior_selected"

  "abilityTree.fallenUltimateLocked|ultimate/fallen"
  "abilityTree.fallenUltimateUnlockable|ultimate/fallen_available"
  "abilityTree.fallenUltimateBlocked|ultimate/fallen_disabled"
  "abilityTree.fallenUltimateUnlocked|ultimate/fallen_selected"

  "abilityTree.battlemonkUltimateLocked|ultimate/battle_monk"
  "abilityTree.battlemonkUltimateUnlockable|ultimate/battle_monk_available"
  "abilityTree.battlemonkUltimateBlocked|ultimate/battle_monk_disabled"
  "abilityTree.battlemonkUltimateUnlocked|ultimate/battle_monk_selected"

  "abilityTree.paladinUltimateLocked|ultimate/paladin"
  "abilityTree.paladinUltimateUnlockable|ultimate/paladin_available"
  "abilityTree.paladinUltimateBlocked|ultimate/paladin_disabled"
  "abilityTree.paladinUltimateUnlocked|ultimate/paladin_selected"

  #abilities
  "abilityTree.whiteAbilityLocked|node/white"
  "abilityTree.whiteAbilityUnlockable|node/white_available"
  "abilityTree.whiteAbilityBlocked|node/white_disabled"
  "abilityTree.whiteAbilityUnlocked|node/white_selected"

  "abilityTree.yellowAbilityLocked|node/yellow"
  "abilityTree.yellowAbilityUnlockable|node/yellow_available"
  "abilityTree.yellowAbilityBlocked|node/yellow_disabled"
  "abilityTree.yellowAbilityUnlocked|node/yellow_selected"

  "abilityTree.purpleAbilityLocked|node/purple"
  "abilityTree.purpleAbilityUnlockable|node/purple_available"
  "abilityTree.purpleAbilityBlocked|node/purple_disabled"
  "abilityTree.purpleAbilityUnlocked|node/purple_selected"

  "abilityTree.blueAbilityLocked|node/blue"
  "abilityTree.blueAbilityUnlockable|node/blue_available"
  "abilityTree.blueAbilityBlocked|node/blue_disabled"
  "abilityTree.blueAbilityUnlocked|node/blue_selected"

  "abilityTree.redAbilityLocked|node/red"
  "abilityTree.redAbilityUnlockable|node/red_available"
  "abilityTree.redAbilityBlocked|node/red_disabled"
  "abilityTree.redAbilityUnlocked|node/red_selected"
)

LOOKUPS_LEATHER_HELMET=(
  "helmet.pale_leather|armor/helmet/pale_leather_helmet"
  "helmet.chainmail|armor/helmet/chainmail_helmet"
  "helmet.pale_chainmail|armor/helmet/pale_chainmail_helmet"
  "helmet.iron|armor/helmet/iron_helmet"
  "helmet.pale_iron|armor/helmet/pale_iron_helmet"
  "helmet.gold|armor/helmet/gold_helmet"
  "helmet.pale_gold|armor/helmet/pale_gold_helmet"
  "helmet.diamond|armor/helmet/diamond_helmet"
  "helmet.pale_diamond|armor/helmet/pale_diamond_helmet"
  "helmet.titanium|armor/helmet/titanium_helmet"
  "helmet.pale_titanium|armor/helmet/pale_titanium_helmet"
  "helmet|armor/helmet|range"
)

LOOKUPS_LEATHER_CHESTPLATE=(
  "chestplate.pale_leather|armor/chestplate/pale_leather_chestplate"
  "chestplate.chainmail|armor/chestplate/chainmail_chestplate"
  "chestplate.pale_chainmail|armor/chestplate/pale_chainmail_chestplate"
  "chestplate.iron|armor/chestplate/iron_chestplate"
  "chestplate.pale_iron|armor/chestplate/pale_iron_chestplate"
  "chestplate.gold|armor/chestplate/gold_chestplate"
  "chestplate.pale_gold|armor/chestplate/pale_gold_chestplate"
  "chestplate.diamond|armor/chestplate/diamond_chestplate"
  "chestplate.pale_diamond|armor/chestplate/pale_diamond_chestplate"
  "chestplate.titanium|armor/chestplate/titanium_chestplate"
  "chestplate.pale_titanium|armor/chestplate/pale_titanium_chestplate"
  "chestplate|armor/chestplate|range"
)

LOOKUPS_LEATHER_LEGGINGS=(
  "leggings.pale_leather|armor/leggings/pale_leather_leggings"
  "leggings.chainmail|armor/leggings/chainmail_leggings"
  "leggings.pale_chainmail|armor/leggings/pale_chainmail_leggings"
  "leggings.iron|armor/leggings/iron_leggings"
  "leggings.pale_iron|armor/leggings/pale_iron_leggings"
  "leggings.gold|armor/leggings/gold_leggings"
  "leggings.pale_gold|armor/leggings/pale_gold_leggings"
  "leggings.diamond|armor/leggings/diamond_leggings"
  "leggings.pale_diamond|armor/leggings/pale_diamond_leggings"
  "leggings.titanium|armor/leggings/titanium_leggings"
  "leggings.pale_titanium|armor/leggings/pale_titanium_leggings"
  "leggings|armor/leggings|range"
)

LOOKUPS_LEATHER_BOOTS=(
  "boots.pale_leather|armor/boots/pale_leather_boots"
  "boots.chainmail|armor/boots/chainmail_boots"
  "boots.pale_chainmail|armor/boots/pale_chainmail_boots"
  "boots.iron|armor/boots/iron_boots"
  "boots.pale_iron|armor/boots/pale_iron_boots"
  "boots.gold|armor/boots/gold_boots"
  "boots.pale_gold|armor/boots/pale_gold_boots"
  "boots.diamond|armor/boots/diamond_boots"
  "boots.pale_diamond|armor/boots/pale_diamond_boots"
  "boots.titanium|armor/boots/titanium_boots"
  "boots.pale_titanium|armor/boots/pale_titanium_boots"
  "boots|armor/boots|range"
)

CACHE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/model-data-cache.XXXXXX")"
declare -A CACHE_FILES=()
OUTPUT_ROWS=()

cleanup() {
  rm -rf "$CACHE_DIR"
}
trap cleanup EXIT

cache_file_key() {
  local file="$1"
  printf '%s' "$file" | tr '/.' '__'
}

ensure_model_cache() {
  local file="$1"
  local full_path="$2"

  if [[ -n "${CACHE_FILES[$file]:-}" ]]; then
    return
  fi

  local cache_file="$CACHE_DIR/$(cache_file_key "$file").tsv"

  jq -r '
    def rows:
      (
        .overrides[]?
        | select(.model? | type == "string")
        | select(.predicate.custom_model_data? != null)
        | [.model, .predicate.custom_model_data]
      ),
      (
        .. | objects
        | select(has("threshold"))
        | select(.model.model? | type == "string")
        | [.model.model, .threshold]
      ),
      (
        .. | objects
        | select(has("threshold"))
        | select(.model.cases?)
        | .model.cases[]
        | select(.model.model? | type == "string")
        | [.model.model, .threshold]
      ),
      (
        .. | objects
        | select(has("threshold"))
        | select(.model.fallback?.model? | type == "string")
        | [.model.fallback.model, .threshold]
      );

    rows
    | select(.[1] != null)
    | [.[0], (.[1] | tonumber)]
    | @tsv
  ' "$full_path" > "$cache_file"

  CACHE_FILES[$file]="$cache_file"
}

extract_values() {
  local file="$1"
  local prefix="$2"
  local cache_file="${CACHE_FILES[$file]}"

  if [ "$type" = "range" ]; then
    awk -F '\t' -v p="$prefix" 'index($1, p) == 1 { print $2 }' "$cache_file"
  else
    awk -F '\t' -v p="$prefix" '$1 == p { print $2 }' "$cache_file"
  fi
}

process_group() {
  local file="$1"
  local group_base="$2"
  shift 2
  local entries=("$@")

  local full_path="$ASSETS_DIR/$file"

  if [ ! -f "$full_path" ]; then
    echo "Missing file: $full_path"
    return
  fi

  ensure_model_cache "$file" "$full_path"

  for entry in "${entries[@]}"; do
    IFS="|" read -r key prefix type <<< "$entry"
    # Assume float if no type provided
    type="${type:-float}"

    IFS=',' read -r -a raw_prefixes <<< "$prefix"

    prefixes=()
    for rp in "${raw_prefixes[@]}"; do
      if [ -n "$group_base" ]; then
        prefixes+=("$MODEL_BASE/$group_base/$rp")
      else
        prefixes+=("$MODEL_BASE/$rp")
      fi
    done

    values=()
    for p in "${prefixes[@]}"; do
      while IFS= read -r match; do
        values+=("$match")
      done < <(extract_values "$file" "$p" "$type")
    done

    if [ ${#values[@]} -eq 0 ]; then
      echo "No values found for $key"
      continue
    fi

    case "$type" in

      float)
        OUTPUT_ROWS+=("float"$'\t'"$key"$'\t'"${values[0]}.0")
        ;;

      range)
        min="${values[0]}"
        max="${values[0]}"
        for value in "${values[@]}"; do
          if (( value < min )); then
            min="$value"
          fi
          if (( value > max )); then
            max="$value"
          fi
        done
        OUTPUT_ROWS+=("range"$'\t'"$key"$'\t'"${min}.0"$'\t'"${max}.0")
        ;;

      *)
        echo "Unknown type: $type"
        continue
        ;;

    esac
  done
}

write_output_json() {
  printf '%s\n' "${OUTPUT_ROWS[@]}" | jq -Rn '
    reduce inputs as $line ({};
      ($line | split("\t")) as $parts
      | if $parts[0] == "float" then
          .floats[$parts[1]] = ($parts[2] | tonumber)
        elif $parts[0] == "range" then
          .ranges[$parts[1]] = [($parts[2] | tonumber), ($parts[3] | tonumber)]
        else
          .
        end
    )
  ' > "$TEMP_OUTPUT"
}

# Define the item file to look in for each lookup group
# First argument is the item file to look in
# Second argument is what to append after "item/wynn", used for groups with many entries
# Third argument is the lookup group to use
echo "Processing misc group"
process_group "potion.json" "" "${LOOKUPS_MISC[@]}"
echo "Processing ability tree group"
process_group "potion.json" "gui/ability_tree" "${LOOKUPS_ABILITY_TREE[@]}"
echo "Processing bows group"
process_group "potion.json" "weapon/archer" "${LOOKUPS_BOWS[@]}"
echo "Processing daggers group"
process_group "potion.json" "weapon/assassin" "${LOOKUPS_DAGGERS[@]}"
echo "Processing wands group"
process_group "potion.json" "weapon/mage" "${LOOKUPS_WANDS[@]}"
echo "Processing reliks group"
process_group "potion.json" "weapon/shaman" "${LOOKUPS_RELIKS[@]}"
echo "Processing spears group"
process_group "potion.json" "weapon/warrior" "${LOOKUPS_SPEARS[@]}"
echo "Processing rings group"
process_group "potion.json" "accessory/ring" "${LOOKUPS_RINGS[@]}"
echo "Processing bracelets group"
process_group "potion.json" "accessory/bracelet" "${LOOKUPS_BRACELETS[@]}"
echo "Processing necklaces group"
process_group "potion.json" "accessory/necklace" "${LOOKUPS_NECKLACES[@]}"
echo "Processing charms group"
process_group "potion.json" "charm" "${LOOKUPS_CHARMS[@]}"
echo "Processing tomes group"
process_group "potion.json" "mastery_tome" "${LOOKUPS_TOMES[@]}"
echo "Processing ingredients group"
process_group "potion.json" "ingredient" "${LOOKUPS_INGREDIENTS[@]}"
echo "Processing materials group"
process_group "potion.json" "economy" "${LOOKUPS_MATERIALS[@]}"
echo "Processing tools group"
process_group "potion.json" "tool" "${LOOKUPS_TOOLS[@]}"
echo "Processing leather helmet group"
process_group "leather_helmet.json" "" "${LOOKUPS_LEATHER_HELMET[@]}"
echo "Processing leather chestplate group"
process_group "leather_chestplate.json" "" "${LOOKUPS_LEATHER_CHESTPLATE[@]}"
echo "Processing leather leggings group"
process_group "leather_leggings.json" "" "${LOOKUPS_LEATHER_LEGGINGS[@]}"
echo "Processing leather boots group"
process_group "leather_boots.json" "" "${LOOKUPS_LEATHER_BOOTS[@]}"

write_output_json
mv "$TEMP_OUTPUT" "$OUTPUT_JSON"
echo "Model Data Updated"
