name: Hash and Format urls.json

on:
  workflow_dispatch:
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
    branches: [main]
  push:
    branches:
      - main
        
jobs:
  hash-format:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4.1.1
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.PRIVATE_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Hash urls.json
        run: |
          chmod +x ./Utils/hash_urls.sh
          ./Utils/hash_urls.sh

      - name: Format urls.json
        run: |
          chmod +x ./Utils/format_urls.sh
          ./Utils/format_urls.sh
            
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: 'WynntilsBot'
          commit_user_email: 'admin@wynntils.com'
          commit_message: 'ci: update urls.json hashes and formatting'